version: "2"
services:
        nodeserver:
                restart: unless-stopped
                image: tdelamater/mistythicketmail:latest
                ports:
                        - "3000:3000"
        nginix:
                restart: unless-stopped
                build:
                        context: ./nginx
                ports:
                        - "8081:80"
                        - "8843:443"
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/error.log:/etc/nginx/error_log.log
                        - /etc/letsencrypt/:/etc/letsencrypt/
